### PR TITLE
project.clj: upgrade to 0.10.3

### LINKED ISSUE #11: Fix CI problem related to unnecessary lein plugin on v0.10.2
This was being discussed in balance https://github.com/tallyfor/balance/pull/2198:

> we should take a look at the error

I can reproduce the problem locally. It started to happen in `re-frame-firebase` on the `master` branch after I merged the PR from @nodename 

On @nodename's PR the problem did not occur:

image

After merging to `master`, it started to occur:

image

It is important to note that even though some errors are reported, it still writes the expected `pom.xml` file.

### PR DESCRIPTION
**Pull request by pdelfino**
hopefully, this fixes #11

### CODE REVIEW

**Comment by jojoucsd** [comment]
Screen Shot 2023-07-26 at 10 14 19 AM
Still seeing the same errors

**Comment by pdelfino** [comment]
Hey @jojoucsd ,

Please, remove the old one from your local `.m2` folder, and try `lein install` again.

I believe it is working and ready to be merged.

**Review by jojoucsd — COMMENTED** [review]
LGTM,
just curious are we using the middleware anywhere?

**Comment by pdelfino** [comment]
> just curious are we using the middleware anywhere?

Not really... It was just an experiment that I was trying to have `deps.edn` and `lein`... This code snippet was like a legacy of such experiments....

The project itself is very experimental. See the README https://github.com/RickMoynihan/lein-tools-deps#do-you-really-want-to-use-this

**Pull request merged**
